# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.2.0
_src_path: https://github.com/Misty02600/nonebot-plugin-template.git
author_email: Misty02600@users.noreply.github.com
author_name: Misty02600
copyright_year: 2026
module_name: nonebot_plugin_triage_help
repo_name: nonebot-plugin-triage-help
repo_owner: Misty02600
